// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
)

type Config struct {
	ID       int64  `json:"id"`
	Uid      string `json:"uid"`
	IsLive   bool   `json:"is_live"`
	SyncType string `json:"sync_type"`
}

type RequestUrl struct {
	ID         int64          `json:"id"`
	Uid        string         `json:"uid"`
	RequestUrl sql.NullString `json:"request_url"`
}

type UrlFirst struct {
	ID      int64          `json:"id"`
	Uid     string         `json:"uid"`
	UrlHash sql.NullString `json:"url_hash"`
}

type UrlSecond struct {
	ID          int64          `json:"id"`
	Uid         sql.NullString `json:"uid"`
	UrlHash     sql.NullString `json:"url_hash"`
	Regex       interface{}    `json:"regex"`
	StartIndex  sql.NullInt32  `json:"start_index"`
	FinishIndex sql.NullInt32  `json:"finish_index"`
}
